# Generated by Django 5.0.2 on 2024-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management_system_app", "0002_studentdetail_proctor_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdetail",
            name="position_level",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
