# Generated by Django 5.0.2 on 2024-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_management_system_app", "0003_alter_staffdetail_position_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetail",
            name="gpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="CID",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="staffdetail",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="CID",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
